### ISSUE TITLE
slick move

### ISSUE THREAD

**Issue by uniformization** [Stefanuk12/RoProPatcher#19]
slick move <https://github.com/Stefanuk12/RoProPatcher/blob/master/src/main.rs#L45>

**Comment by Stefanuk12** [comment]
i was going to remove that but it didn't really make much of a difference. 

reason that was there is because i was trying to make it send their cookie as stated [here](https://github.com/Stefanuk12/RoProPatcher/commit/c875e58ce2f5d75e78f1cd5719222eabe86290f1).

i don't think it worked unfortunately. anyway, i was looking for it to send the phpsessid cookie across for some reason i forgot.

if you're worried about it stealing your roblox cookie, it won't since ropro doesn't send your cookie to their servers and therefore the proxy due to cors

**Comment by uniformization** [comment]
my bad, i didn't know jquery and i assumed the worse. i figured earlier that it would provide the cookies to the proxy requests and figured you were funneling cookies that way.

**Comment by Stefanuk12** [comment]
Letting you know, since I had to make an update, I decided to remove it. 😁
